---
title: "gen_data"
date: "2024-02-23"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
```
## This converts the data into a more usable format and exports it to csv.

https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-09-01/readme.md
```{r}
  read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/key_crop_yields.csv') |> 
  filter(Entity=="United States") |> 
  select_if(~ !any(is.na(.))) |> #drops columns with NAs
  select(!c(Code, Entity)) |> 
  pivot_longer(cols=-Year, names_to = c('commodity', NA), names_sep = ' \\(') |> 
  rename(year=Year, tonnes_per_ha=value) |> 
  mutate(commodity = tolower(commodity)) |> 
  mutate(commodity = case_when(commodity == "maize" ~ "corn",
                   TRUE ~ commodity)) |> 
  write_csv(file='clean_data/us_crop_data.csv')
```

https://www.kaggle.com/datasets/berkeleyearth/climate-change-earth-surface-temperature-data
```{r}
read_csv("raw_data/GlobalLandTemperaturesByState.csv") |> 
  filter(State=='Wisconsin') |> 
  mutate(year=year(dt)) |>
  filter(year>1780) |> #when data starts reliably having a measurement every month
  group_by(year) |> 
  summarize(avg_temp = mean(AverageTemperature), avg_temp_uncertainty=mean(AverageTemperatureUncertainty)) |> 
  write_csv(file='clean_data/wisconsin_global_land_temps.csv')
```

https://quickstats.nass.usda.gov/results/1257F09F-FF9A-36F6-B1E7-05F8AF2058FE

```{r}
read_csv("raw_data/C4B8556B-0E81-390D-B111-D1013BEA7A3B.csv") |> 
  filter(Period=="YEAR") |> 
  select(Year, Commodity, Value) |> 
  mutate(Value = case_when(Commodity=='BARLEY' ~ Value*.0538, #apparently bushels are different
         Commodity=='CORN' ~ Value*.0628,
         TRUE ~ Value*.0673)) |> 
  rename(year=Year, commodity=Commodity, tonnes_per_ha=Value) |> 
  mutate(commodity = tolower(commodity)) |> 
  write_csv(file='clean_data/wisconsin_nass_yields.csv')
```

https://www.census.gov/data/tables/time-series/dec/popchange-data-text.html
```{r}
census <- read_csv("https://www2.census.gov/programs-surveys/decennial/2020/data/apportionment/apportionment.csv")
census |> filter(Name=="United States") |> 
  select(Year, `Resident Population`) |> 
  rename(year=Year, pop=`Resident Population`) |> 
  write_csv(file='clean_data/us_census.csv')

census |> filter(Name=="Wisconsin") |> 
  select(Year, `Resident Population`) |> 
  rename(year=Year, pop=`Resident Population`) |> 
  write_csv(file='clean_data/wi_census.csv')
```

https://www.ncei.noaa.gov/access/monitoring/climate-at-a-glance/statewide/time-series/47/pcp/ytd/12/1895-2023
```{r}
read_csv("https://www.ncei.noaa.gov/access/monitoring/climate-at-a-glance/statewide/time-series/47/pcp/1/0/1895-2023.csv", 
         skip=4, col_names = c("date", "precipitation")) |> 
  left_join(read_csv("https://www.ncei.noaa.gov/access/monitoring/climate-at-a-glance/statewide/time-series/47/tavg/1/0/1895-2023.csv",
                     skip=4, col_names=c("date", "avg_temp"))) |> 
  left_join(read_csv("https://www.ncei.noaa.gov/access/monitoring/climate-at-a-glance/statewide/time-series/47/tmax/1/0/1895-2023.csv",
                     skip=4, col_names=c("date", "max_temp"))) |> 
  left_join(read_csv("https://www.ncei.noaa.gov/access/monitoring/climate-at-a-glance/statewide/time-series/47/tmin/1/0/1895-2023.csv",
                     skip=4, col_names=c("date", "min_temp"))) |>
  mutate(date = (ym(date))) |> 
  write_csv("clean_data/monthly_wi_weather.csv")
```

