---
title: "project"
output: html_document
date: "2024-02-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
```

```{r}
wi_yields <- read_csv("clean_data/wisconsin_nass_yields.csv")
us_yields <- read_csv("clean_data/us_crop_data.csv")
```

```{r}
ggplot(wi_yields)+
  geom_line(aes(year, tonnes_per_ha, color=commodity))+
  labs(x="Year", y="Tonnes Per Hectacre", color="Commodity")
```

```{r}
ggplot(us_yields)+
  geom_line(aes(year, tonnes_per_ha, color=commodity))+
  labs(x="Year", y="Tonnes Per Hectacre", color="Commodity")
```
```{r}
us_yields |> filter(commodity=="barley"|commodity=="corn"|commodity=="soybeans"|commodity=="wheat") |> 
  bind_rows(wi_yields, .id="level") |> 
  mutate(level = case_when(level==1 ~ "US",
                           TRUE ~ "Wisconsin")) |> 
  filter(year>1960) |> 
  ggplot()+
    geom_line(aes(year, tonnes_per_ha, color=commodity))+
    facet_grid(level~.) +
    labs(x="Year", y="Tonnes Per Hectacre", color="Commodity")
```
```{r}
wi_weather <- read_csv("clean_data/monthly_wi_weather.csv")
wi_weather
```
```{r}
wi_weather |> 
  group_by(year = year(date)) |> 
  summarize(max_temp=max(max_temp), avg_temp=mean(avg_temp), min_temp=min(min_temp)) |> 
  pivot_longer(cols=-year, names_to="Temperature") |> 
  ggplot(aes(year, value))+
  geom_line(aes(color=Temperature))+
  labs(title="Wisconsin Temperatures", x="Year", y="Temp in F")+
  scale_color_manual(labels = c("Average", "Max", "Min"),
                     values = c("green", "red", "blue"))
```

```{r}
p1<-ggplot(wi_yields)+
  geom_line(aes(year, tonnes_per_ha, color=commodity))+
  labs(x="", y="Tonnes Per Hectacre", color="Commodity")
p2<-wi_weather |> 
  group_by(year = year(date)) |> 
  summarize(precipitation=sum(precipitation)) |> 
  filter(year>1923) |> 
  ggplot()+
  geom_line(aes(year, precipitation))+
  labs(x="Year", y="Precipitation (inches)")
p1/p2+
  plot_annotation("Wisconsin Annual Crop Yields vs Annual Precipitation")
```
```{r}
wi_yields
```

